### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by 75lb** [75lb/baldrick#5]
- [ ] `baldrick '(.*)\.scss' '$1.css'` - bake in renamer functionality? need to specify multiple commands, watch several sass files (all writing to sep output files) simultaneously
- [ ] add `--test` option which measures the time between file modified and baldrick response
- [ ] add option to use `fs.watch` - it might work for some users, e.g. vim users (editors which edit a file directly, not via a proxy file)
- [ ] `--when *.js` doesn't pick up a new js file after baldrick is started.. 
  would prefer this:
  `--do <this> --when <directory> --updated` (picking up new, deleted and updated files)
- [ ] syntax, similar to time.. commands add to background watcher?

``` sh
baldrick --when *.scss --change --do sass input output 
baldrick --when templates/ --updated --do handlebars tempates/*.hbs
```
